language: cpp

sudo: false

git:
  depth: 1500

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - CONFOPTS=""

matrix:
  include:
    ## make distcheck
    - os: linux
      compiler: gcc
      env: DISTCHECK="yes"
           CONFOPTS=""
    # test old Ubuntu 12.04 and OSX for compatibility
    - dist: precise
      compiler: gcc
      env: PRECISE="yes" CONFOPTS=""

addons:
  apt:
    packages:
      - gengetopt
      - help2man

install:
  - env | grep -v "encrypted" | LC_ALL=C sort
  - lscpu || sysctl hw
  - source ./.travis-functions.sh
  - travis_have_sudo
  - travis_install_script

before_script:
  - travis_before_script

script:
  - travis_script

branches:
  only:
    - master
    - next
    - /^travis.*/
    - /^tmp.*/
